const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Idook-backend",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
        JWT: {
            type: 'apiKey',
            description: 'Authorização para poder acessar a API',
            name: 'Authorization',
            in: 'header',
          },
    }
}
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/app.js')
})